// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC79m_TOHB__myFfrgMWnc62ziE82j4dJU',
    appId: '1:639051625163:web:98c528f65d6a62b5fe614e',
    messagingSenderId: '639051625163',
    projectId: 'my-food-cd612',
    authDomain: 'my-food-cd612.firebaseapp.com',
    storageBucket: 'my-food-cd612.appspot.com',
    measurementId: 'G-H6V1VMHDRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7-uvrqzOKzfY0IvYMOG1xSNtXQKsVDsM',
    appId: '1:639051625163:android:fff3c5889b8e8cb5fe614e',
    messagingSenderId: '639051625163',
    projectId: 'my-food-cd612',
    storageBucket: 'my-food-cd612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS995-teawk0a572JXAlQ3TvKnSQu3a88',
    appId: '1:639051625163:ios:f4f03bf82a59a51cfe614e',
    messagingSenderId: '639051625163',
    projectId: 'my-food-cd612',
    storageBucket: 'my-food-cd612.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS995-teawk0a572JXAlQ3TvKnSQu3a88',
    appId: '1:639051625163:ios:f4f03bf82a59a51cfe614e',
    messagingSenderId: '639051625163',
    projectId: 'my-food-cd612',
    storageBucket: 'my-food-cd612.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC79m_TOHB__myFfrgMWnc62ziE82j4dJU',
    appId: '1:639051625163:web:83dd9329b1f44247fe614e',
    messagingSenderId: '639051625163',
    projectId: 'my-food-cd612',
    authDomain: 'my-food-cd612.firebaseapp.com',
    storageBucket: 'my-food-cd612.appspot.com',
    measurementId: 'G-4QQ58EHWJ6',
  );
}
